### ISSUE TITLE
Powell_XMLParser: no targets entered

### ISSUE THREAD

**Issue by wanyuac** [danny-wilson/genomegaMap#1]
Hi Danny,

I have compiled genomegaMap from source code but I encountered an error with the message: "ERROR: Powell_XMLParser: no targets entered".

Full Linux command line and output:
```bash
export LD_LIBRARY_PATH=$HOME/software/genomegaMap:$HOME/software/gcat-project:$HOME/anaconda3/envs/raxml/lib

~/software/gcat-project/gcat ~/software/genomegaMap/examples/porB3.genomegaMapConstantML.a.xml
ERROR: Powell_XMLParser: no targets entered
```

For your reference, packages installed on my HPC are:
```bash
gcc_linux-64 7.3.0
gxx_linux-64 7.3.0
xerces-c 3.2.3
gsl 2.6
libstdcxx-ng 9.1.0
```

Since my HPC does not allow me to install Docker or Singularity but Conda, these packages were installed throught Conda. Command lines used for compiling gcat and genomegaMap are:

```bash
git clone https://github.com/danny-wilson/gcat-project.git
cd gcat-project
make INCLUDE="-Isrc -I$HOME/anaconda3/envs/raxml/include -I$HOME/software/gcat-project/src/myutils" LNK_OPTIONS="-Wl,--no-as-needed -lxerces-c -L$HOME/anaconda3/envs/raxml/lib -L./"

git clone https://github.com/danny-wilson/genomegaMap.git
cd genomegaMap
make INCLUDE="-Isrc -I../gcat-project/src -I../gcat-project/src/myutils -I$HOME/anaconda3/envs/raxml/include" LNK_OPTIONS="-Wl,--no-as-needed -lxerces-c -L$HOME/anaconda3/envs/raxml/lib -L../gcat-project"
```

Both commands finished successfully, with the following output files:
```bash
ls $HOME/software/gcat-project
Dockerfile  Dockerfile.FromBinaries  examples  gcat  gcat.def  libgammaMap.so  libgcat-core.so  makefile  makefile.backup  README.txt  src

ls $HOME/software/genomegaMap
Dockerfile  examples  libgenomegaMap.so  LICENSE  makefile  README.txt  src
```

I would sincerely appreicate it if you could give me any advice about this issue. Thanks.

**Comment by danny-wilson** [comment]
Dear Yu Wan,

Thanks for the message and your interest in the tool.

I am sorry but it is not apparent to me what the problem is here. I'm not
familiar with Conda.

At a guess, perhaps this is an issue with XercesC, based on the error
message. I believe I used version 3.1.1 in the Docker image.

Perhaps you could try the Docker or Singularity container on a machine you
can run them on, and compare the versions of the libraries.

best wishes,
Danny

**Comment by wanyuac** [comment]
Dear Danny,

Thank for your reply. I did a fresh installation from Singularity but unfortunately, the problem remains the same. My command lines are:

```bash
cd ~/app  # An empty directory for the standalone version of genomegaMap

singularity pull -F docker://dannywilson/genomegamap  # genomegamap_latest.sif appears

singularity run genomegamap_latest.sif
ERROR: SYNTAX: gcat xmlfile  # Expected output

curl -LJO https://raw.githubusercontent.com/danny-wilson/genomegaMap/master/examples/porB3.genomegaMapConstantML.a.xml
curl -LJO https://raw.githubusercontent.com/danny-wilson/genomegaMap/master/examples/porB3.carriage.noindels.txt

singularity run genomegamap_latest.sif porB3.genomegaMapConstantML.a.xml
ERROR: Powell_XMLParser: no targets entered
```

My system is an HPC running the following Linux release:
```bash
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

In addition, this problem seems to be independent to Linux versions as I compiled both gcat and genomegaMap on my personal Xubuntu system (Ubuntu 18.04.4 LTS), to which I have administrative control, the same error message still occurred. (GCC and G++: v6.4.0; xerces-c: v3.1.1; libgcc: v5.2.0; gsl: v2.6) Direct installation of the Docker image through singularity on my Xubuntu did not solve the issue either.

**Comment by danny-wilson** [comment]
Thanks again for raising this issue. I've made two fixes: the example file in question had a misplaced comment in the <powell> section, and the GenomegaMap guide page 7 had a typo in the Singularity section re: copying the example files. The updated Release v1.0.1 addresses these issues.

best wishes,
Danny

**Comment by wanyuac** [comment]
Dear Danny,

Yes, as you have pointed out, the analysis went through successfully after moving the comment out of the <powell></powell> block in the XML file. Many thanks for solving this issue! It is of great help to us.
