### ISSUE TITLE
Error: DNA::tripletToCodon61():

### ISSUE THREAD

**Issue by EstefaniaSanch** [danny-wilson/genomegaMap#7]
Hi, thanks for this useful tool.
I am trying to run the program in Docker, I started with the examples and files you provide and they run fine (byB3.genomegaMapConstantML.a.xml), it gave me the statistical results of theta, kappa and omega which are the ones I need at the moment. However, when I submitted the same file but specifying my fasta sequences, I get this error:
ERROR: DNA::tripletToCodon61(): STOP codon found

I already tried to modify the file, make it with less sequences and it doesn't run.

I hope you can help me or suggest me what to do

Thanks in advance 

Translated with DeepL.com (free version)

**Comment by marianajeeb8** [comment]
Hello,

I am encountering the same error. I am also running it with Docker. It worked fine for some data files, however, with other files giving me error as mentioned above.

I hope to get help in this regard!
Maria

**Comment by danny-wilson** [comment]
Hello, this means a stop codon was found in your alignment. Try removing them.
